spring:
  profiles:
    active: development
  data:
    rest:
      base-path: /api

---
spring:
  profiles: development

taco:
  security:
    sampleUserName: andy
    samplePassword: 1234
    sampleUserRole: USER